rankups:
    C:
      icon: STONE
      requirements:
        "1":
            type: org.stevenw.prison.rankup.requirements.RequirementGroup
            value: D
            material: DIRT
        "2":
            type: org.stevenw.prison.rankup.requirements.RequirementMoney
            value: 30000
        "3":
            type: org.stevenw.prison.rankup.requirements.RequirementItem
            value:
                type: COAL
                amount: 12
        "4":
            type: org.stevenw.prison.rankup.requirements.RequirementItem
            value:
                type: DIAMOND
                amount: 2
    B:
      icon: LEAVES
      requirements:
        "1":
            type: org.stevenw.prison.rankup.requirements.RequirementGroup
            value: C			
        "2":
            type: org.stevenw.prison.rankup.requirements.RequirementMoney
            value: 125000
        "3":
            type: org.stevenw.prison.rankup.requirements.RequirementItem
            value:
                type: GOLD_INGOT
                amount: 12
    A:
      icon: ICE
      requirements:
        "1":
            type: org.stevenw.prison.rankup.requirements.RequirementGroup
            value: B			
        "2":
            type: org.stevenw.prison.rankup.requirements.RequirementMoney
            value: 375000
        "3":
            type: org.stevenw.prison.rankup.requirements.RequirementItem
            value:
                type: DIAMOND
                amount: 12
    M:
      icon: WOOL
      requirements:
        "1":
            type: org.stevenw.prison.rankup.requirements.RequirementGroup
            value: A		
        "2":
            type: org.stevenw.prison.rankup.requirements.RequirementMoney
            value: 1500000
        "3":
            type: org.stevenw.prison.rankup.requirements.RequirementItem
            value:
                type: DIAMOND
                amount: 64
        "3":
            type: org.stevenw.prison.rankup.requirements.RequirementItem
            value:
                type: IRON_BLOCK
                amount: 32
    S:
      icon: GRASS
      requirements:
        "1":
            type: org.stevenw.prison.rankup.requirements.RequirementGroup
            value: M
        "2":
            type: org.stevenw.prison.rankup.requirements.RequirementMoney
            value: 4750000
        "3":
            type: org.stevenw.prison.rankup.requirements.RequirementItem
            value:
                type: DIAMOND
                amount: 64
        "4":
            type: org.stevenw.prison.rankup.requirements.RequirementItem
            value:
                type: MOSSY_COBBLESTONE
                amount: 256
    R:
      icon: GRASS
      requirements:
        "1":
            type: org.stevenw.prison.rankup.requirements.RequirementGroup
            value: S
        "2":
            type: org.stevenw.prison.rankup.requirements.RequirementMoney
            value: 12500000
